apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecr-app
  template:
    metadata:
      labels:
        app: ecr-app
    spec:
      containers:
        - name: nginx
          image: 159831708372.dkr.ecr.us-east-1.amazonaws.com/devops:nginx-v1
          ports:
            - containerPort: 80
