apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecr-app
  template:
    metadata:
      labels:
        app: ecr-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
